# Copyright (c) 2020 Shawn Eary
#
# Makefile for Cheese
#
# Cheese is Licenced via the MIT License
#
# When this music piece is done, hopefully it won't give you too much
# gas...
default: 
	ghc cheese.hs ../../reuse/audioFormat.hs ../../reuse/intConversion.hs ../../reuse/generators.hs
