# Copyright (c) 2019 Shawn Eary
#
# Makefile for RefWave
#
# RefWave is Licenced via the MIT License
default: 
	ghc refWave.hs ../../reuse/audioFormat.hs ../../reuse/intConversion.hs ../../reuse/generators.hs
